[book]
authors = ["Pextra Inc."]
language = "en"
src = "src"
title = "Pextra Documentation"
description = "User documentation for the Pextra CloudEnvironmentÂ® private cloud management platform."

[output.html]
default-theme = "rust"
preferred-dark-theme = "navy"
smart-punctuation = true
git-repository-url = "https://github.com/PextraCloud/documentation/tree/master/cloudenvironment"
edit-url-template = "https://github.com/PextraCloud/documentation/edit/master/cloudenvironment/{path}"
site-url = "/cloudenvironment/"

[output.html.fold]
enable = true
level = 2

[output.markdown]
[output.llms-txt]
[output.llms-txt-full]